#pragma once
#include "DiracOperator/GenerateOperator.hpp"
#include "DiracOperator/Operators/Ek.hpp"
#include "DiracOperator/Operators/Hyperfine.hpp"
#include "DiracOperator/Operators/M1.hpp"
#include "DiracOperator/Operators/PNC.hpp"
#include "DiracOperator/Operators/QED.hpp"
#include "DiracOperator/Operators/RadialF.hpp"
#include "DiracOperator/TensorOperator.hpp"
