name: Build (linux)

on:
  push:
    branches: [ "main", "dev", "TestWorkflows" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build_latest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++-13, clang++-15]  # Test with both g++ and clang++
        openmp: [yes, no]               # Test with and without OpenMP support

    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v4

    # Step 2: Install dependencies
    - name: "Install dependencies"
      run: |
        set -x
        sudo apt-get update -y
        # Install build tools and compilers
        sudo apt-get install -y make 
        sudo apt-get install -y g++-13
        sudo apt-get install -y clang-15
        # Install scientific libraries
        sudo apt-get install -y liblapack-dev
        sudo apt-get install -y libblas-dev
        sudo apt-get install -y libgsl-dev
        # OMP: must match clang version
        sudo apt-get install -y libomp-15-dev

    # Step 3: Set up the environment
    - name: "Set up environment"
      run: |
        cp ./doc/examples/Makefile ./
        cp ./doc/examples/ampsci.in ./ampsci.in

    # Step 4: Build the project using the matrix configuration
    - name: "Build ampsci"
      run: make clean && make CXX=${{ matrix.compiler }} UseOpenMP=${{ matrix.openmp }}

    # Step 5: Run the project with the input file
    - name: "Run ampsci"
      run: ./ampsci ampsci.in