name: Docs

on:
  push:
    branches: [ "main" ]

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: "Install dependencies"
      run: |
        set -x
        sudo apt-get update -y
        sudo apt-get install -y make
        sudo apt-get install -y doxygen
        sudo apt-get install -y texlive-latex-extra --fix-missing
        sudo apt-get install -y wget
    
    - name: Build the documentation
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch
        git checkout gh-pages
        git reset --hard origin/main
        cp ./doc/examples/Makefile ./ 
        for FILE in ./doc/*.md; do sed -i 's%(/doc/%(doc/%g' $FILE; done
        for FILE in ./doc/*.md; do sed -i 's%(/README%(README%g' $FILE; done
        for FILE in ./doc/*.md; do sed -i 's%(/src/%(https://github.com/benroberts999/ampsci/tree/main/src/%g' $FILE; done
        for FILE in ./doc/*.md; do sed -i 's%::::%\brief%g' $FILE; done
        for FILE in ./doc/tutorial*.md; do sed -i -e 's/\$\$~/\\f\[/g' $FILE; done
        for FILE in ./doc/tutorial*.md; do sed -i -e 's/~\$\$/\\f\]/g' $FILE; done
        for FILE in ./doc/tutorial*.md; do sed -i -e 's/\$/\\f\$/g' $FILE; done
        sed -i 's%tests-badge]]%tests-badge-v2]]%g' ./README.md
        sed -i 's%build-badge]]%build-badge-v2]]%g' ./README.md
        sed -i 's%macOS-badge]]%macOS-badge-v2]]%g' ./README.md
        sed -i 's%cov-badge]]%cov-badge-v2]]%g' ./README.md
        rm -rf ./docs/form_*.png
        rm -rf ./docs/formula.repository
        make doxy
        wget https://cdn.mathjax.org/mathjax/latest/MathJax.js -O ./docs/MathJax.js
        echo ampsci.dev > ./docs/CNAME
        wget https://github.com/benroberts999/ampsci/actions/workflows/tests.yml/badge.svg -O ./docs/tests-badge.svg
        wget https://github.com/benroberts999/ampsci/actions/workflows/build.yml/badge.svg -O ./docs/build-badge.svg
        wget https://github.com/benroberts999/ampsci/actions/workflows/macOS.yml/badge.svg -O ./docs/macOS-badge.svg
        wget https://codecov.io/gh/benroberts999/ampsci/branch/main/graph/badge.svg -O ./docs/cov-badge.svg

    - name: Commit+push documentation to gh-pages
      run: |
        git add .
        git add docs/* -f
        git commit -a -m "Make documentation [GH Actions]"
        git push origin gh-pages -f